# Generated by Django 5.2.7 on 2026-05-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_apply_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posting_source',
            field=models.CharField(choices=[('post', 'Post'), ('share', 'Share')], default='post', max_length=20),
        ),
    ]
