# Generated by Django 6.0.3 on 2026-04-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HR', 'hr'), ('SEEKER', 'seeker')], max_length=10),
        ),
    ]
