# Generated by Django 6.0.3 on 2026-04-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otp_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio about yourself', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.JSONField(blank=True, default=list, help_text='List of work experience: [{title, company, start_date, end_date, description, current}]'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Job search preferences: {job_types, locations, experience_level, salary_min, salary_max}'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of skills'),
        ),
    ]
