# Generated by Django 6.0.3 on 2026-05-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_permission_userpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(default=False, help_text='Whether user has moderation permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HR', 'hr'), ('SEEKER', 'seeker'), ('ADMIN', 'admin')], max_length=10),
        ),
    ]
