# Generated by Django 6.0.3 on 2026-03-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=40)),
                ('middleName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone', models.BigIntegerField(max_length=10, unique=True)),
            ],
        ),
    ]
